version: '3'
services:
    opain-app:
        container_name: opain-app
        image: mine2023/opainfront
        restart: on-failure
        ports: 
            - 4200:4200
        environment: 
            WAIT_HOSTS: mine2023/opainservice:8000
        depends_on: 
            - opain-services 
    opain-services:
        container_name: opain-services
        image: mine2023/opainservice
        restart: always
        ports:
            - 8000:8000